# This is a basic workflow to help you get started with Actions

name: Deploy to DigitalOcean and Start Deno Server

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Setup repo
      - uses: actions/checkout@v3

      - name: SSH Deploy
        uses: easingthemes/ssh-deploy@main
        with:
            # Private Key
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            # Remote host
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }} 
            # Remote user
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            # Remote port
            REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
            # Source directory
            SOURCE: $GITHUB_WORKSPACE
            # Target directory
            TARGET: ${{ secrets.REMOTE_TARGET }}
#             # Arguments to pass to rsync
            ARGS: "-rltgoDzvO" 

      - name: Setup Deno server
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Cache Dependencies
        run: deno cache deps.ts 

      - name: Deploy Server
        run: deno run -A main.ts --allow-net --allow-read --allow-env