# This is a basic workflow to help you get started with Actions

name: Deploy to DigitalOcean

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: SSH Deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
            # Private Key
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            # Remote host
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }} 
            # Remote user
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            # Source directory
            SOURCE: $GITHUB_WORKSPACE
            # Target directory
            REMOTE_TARGET: ${{ secrets.REMOTE_TARGET }}    

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }} # tests across multiple Deno versions

      - name: Cache Dependencies
        run: deno cache deps.ts

      - name: Run Deno Server
        run: deno run -A main.ts --allow-net --allow-read --allow-env